#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
 
bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^6' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Pycalendar.py state=floating rectangle=600x400+660+51
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Border
. "$HOME/.cache/wal/colors.sh"
bspc config focused_border_color        "$color5"
bspc config normal_border_color         "$color2"
bspc config active_border_color         "$color2"
bspc config presel_feedback_color       "$color2"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Nvidia sleep error fix
nvidia-sleep-fix &
# Keyboard layout
setxkbmap -layout us -variant altgr-intl &
# Bar
~/.config/polybar/launch.sh --docky &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
wal -R &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
picom -b &
# Network Applet
nm-applet --indicator &
# Cursor
xsetroot -cursor_name left_ptr &
# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

